# Generated by Django 5.0.6 on 2024-07-01 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softmatterdata",
            options={"managed": True},
        ),
    ]
