# Generated by Django 5.0.6 on 2024-07-01 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_softmatterdata_sample_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softmatterdata",
            name="lastupdate",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 4, 30, 23, 69248, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
