# Generated by Django 5.0.6 on 2024-07-01 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_softmatterdata_lastupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="softmatterdata",
            name="meta_data",
            field=models.FileField(blank=True, null=True, upload_to="metadata/"),
        ),
        migrations.AlterField(
            model_name="softmatterdata",
            name="lastupdate",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 1, 18, 20, 53, 258595, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
