# Generated by Django 5.0.6 on 2024-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_softmatterdata_meta_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softmatterdata",
            name="lastupdate",
            field=models.DateField(auto_now=True),
        ),
    ]
