# Generated by Django 5.0.6 on 2024-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_softmatterdata_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "compositiontable",
                "managed": True,
            },
        ),
    ]
