# Generated by Django 5.0.6 on 2024-07-02 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_compositiontypes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompositionTypes",
        ),
    ]
