# Generated by Django 5.0.6 on 2024-07-02 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_compositions_alter_softmatterdata_composition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softmatterdata",
            name="composition",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Compositions",
        ),
    ]
