# Generated by Django 5.0.6 on 2024-07-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_softmatterdata_composition_delete_compositions"),
    ]

    operations = [
        migrations.AddField(
            model_name="softmatterdata",
            name="additional_resources",
            field=models.FileField(blank=True, null=True, upload_to="add_rec/"),
        ),
    ]
