# Generated by Django 5.0.6 on 2024-09-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_softmatterdata_additional_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='softmatterdata',
            name='users',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
