# Generated by Django 5.0.6 on 2024-09-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_softmatterdata_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softmatterdata',
            name='users',
        ),
        migrations.AddField(
            model_name='softmatterdata',
            name='barcode_data',
            field=models.FileField(blank=True, null=True, upload_to='barcode/'),
        ),
    ]
