# Generated by Django 5.0.6 on 2024-09-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_softmatterdata_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softmatterdata',
            name='barcode_data',
        ),
    ]
