# Generated by Django 5.0.6 on 2024-09-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_softmatterdata_barcode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='softmatterdata',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='add_rec/'),
        ),
        migrations.AddField(
            model_name='softmatterdata',
            name='barcode_display',
            field=models.FileField(blank=True, null=True, upload_to='add_rec/'),
        ),
    ]
