# Generated by Django 5.0.6 on 2024-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_softmatterdata_barcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softmatterdata',
            old_name='additional_resources',
            new_name='additional_resources1',
        ),
        migrations.AddField(
            model_name='softmatterdata',
            name='additional_resources2',
            field=models.FileField(blank=True, null=True, upload_to='add_rec/'),
        ),
        migrations.AddField(
            model_name='softmatterdata',
            name='additional_resources3',
            field=models.FileField(blank=True, null=True, upload_to='add_rec/'),
        ),
        migrations.AlterField(
            model_name='softmatterdata',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='softmatterdata',
            name='barcode_display',
            field=models.FileField(blank=True, null=True, upload_to='display/'),
        ),
    ]
